# 这是一份示例
# ================================
server:
    port: "7093"
    static: "public"
    templateDir: "views"
    isOpenSupportSpa: 0

database:
    dbname: "cb_toolbox"
    username: "root"
    password: "123456"
    address: "localhost:3306"

cacher:
    db: 0
    password: ""
    address: "localhost:6379"

logger:
    type: "console"
    # Warn, Notice, Info, Debug, Trace, Panic, Fatal, Error
    levels:
        - "Warn"
        - "Notice"
        - "Info"
        - "Debug"
        - "Trace"
        - "Panic"
        - "Fatal"
        - "Error"
    file: "logs/app.log"